import React, { createContext, useContext, useState, useEffect } from 'react';
import { dbService } from '../services/db';

type Language = 'ar' | 'fr' | 'en';

interface Translations {
  [key: string]: {
    ar: string;
    fr: string;
    en: string;
  };
}

export const translations: Translations = {
  dashboard: { ar: 'لوحة التحكم', fr: 'Tableau de bord', en: 'Dashboard' },
  overtime_dashboard: { ar: 'لوحة قياس الساعات الإضافية', fr: 'Tableau de bord des heures supplémentaires', en: 'Overtime Dashboard' },
  dashboard_summary: { ar: 'ملخص لوحة التحكم', fr: 'Résumé du tableau de bord', en: 'Dashboard Summary' },
  teachers: { ar: 'الأساتذة', fr: 'Enseignants', en: 'Teachers' },
  specialties: { ar: 'التخصصات', fr: 'Spécialités', en: 'Specialties' },
  schedules: { ar: 'الجداول', fr: 'Emplois du temps', en: 'Schedules' },
  projects: { ar: 'مشاريع التخرج', fr: 'Projets de fin d\'études', en: 'Graduation Projects' },
  calendar: { ar: 'الرزنامة', fr: 'Calendrier', en: 'Calendar' },
  sessions: { ar: 'متابعة الحصص', fr: 'Suivi des séances', en: 'Session Tracking' },
  compensation: { ar: 'التعويضات', fr: 'Compensations', en: 'Compensations' },
  department_stats: { ar: 'إحصائيات القسم', fr: 'Statistiques du département', en: 'Department Statistics' },
  general_info: { ar: 'معلومات عامة', fr: 'Informations générales', en: 'General Information' },
  license_phase: { ar: 'طور الليسانس', fr: 'Phase Licence', en: 'License Phase' },
  master_phase: { ar: 'طور الماستر', fr: 'Phase Master', en: 'Master Phase' },
  engineers_phase: { ar: 'طور المهندسين', fr: 'Phase Ingénieurs', en: 'Engineers Phase' },
  teaching_staff: { ar: 'هيئة التدريس', fr: 'Corps enseignant', en: 'Teaching Staff' },
  infrastructure: { ar: 'الهياكل القاعدية', fr: 'Infrastructure', en: 'Infrastructure' },
  specialized_teaching: { ar: 'التعليم المتخصص', fr: 'Enseignement spécialisé', en: 'Specialized Teaching' },
  support_staff: { ar: 'طاقم الدعم', fr: 'Personnel de soutien', en: 'Support Staff' },
  international_students: { ar: 'الطلبة الدوليين', fr: 'Étudiants internationaux', en: 'International Students' },
  groups: { ar: 'الأفواج', fr: 'Groupes', en: 'Groups' },
  amphitheaters: { ar: 'المدرجات', fr: 'Amphithéâtres', en: 'Amphitheaters' },
  td_rooms: { ar: 'قاعات TD', fr: 'Salles TD', en: 'TD Rooms' },
  tp_rooms: { ar: 'قاعات TP', fr: 'Salles TP', en: 'TP Rooms' },
  tp_computers: { ar: 'أجهزة كمبيوتر TP', fr: 'Ordinateurs TP', en: 'TP Computers' },
  lab_seats: { ar: 'مقاعد المخبر', fr: 'Places en labo', en: 'Lab Seats' },
  consumables_sufficiency: { ar: 'كفاية المستهلكات (%)', fr: 'Suffisance des consommables (%)', en: 'Consumables Sufficiency (%)' },
  teaches_ai: { ar: 'يدرس الذكاء الاصطناعي', fr: 'Enseigne l\'IA', en: 'Teaches AI' },
  teaches_entrepreneurship: { ar: 'يدرس المقاولاتية', fr: 'Enseigne l\'entrepreneuriat', en: 'Teaches Entrepreneurship' },
  it_engineers: { ar: 'مهندسو الإعلام الآلي', fr: 'Ingénieurs informatiques', en: 'IT Engineers' },
  it_technicians: { ar: 'تقنيو الإعلام الآلي', fr: 'Techniciens informatiques', en: 'IT Technicians' },
  admin_workers: { ar: 'الموظفون الإداريون', fr: 'Agents administratifs', en: 'Administrative Workers' },
  search_teachers: { ar: 'البحث عن الأساتذة...', fr: 'Rechercher des enseignants...', en: 'Search teachers...' },
  failed_to_generate_account: { ar: 'فشل في إنشاء الحساب.', fr: 'Échec de la génération du compte.', en: 'Failed to generate account.' },
  auth_creation_failed: { ar: 'فشل إنشاء حساب الدخول', fr: 'Échec de la création du compte d\'authentification', en: 'Auth account creation failed' },
  user_already_existed_linked: { ar: 'تم ربط الحساب الموجود مسبقاً بنجاح', fr: 'Compte existant lié avec succès', en: 'Existing account linked successfully' },
  teacher_added_locally: { ar: 'تمت إضافة بيانات الأستاذ محلياً (بدون حساب دخول حالياً)', fr: 'Enseignant ajouté localement (sans compte d\'accès)', en: 'Teacher added locally (no access account currently)' },
  no_auth: { ar: 'بدون حساب', fr: 'Sans compte', en: 'No Account' },
  loading: { ar: 'جاري التحميل...', fr: 'Chargement...', en: 'Loading...' },
  mechanical_engineering_example: { ar: 'مثال: الهندسة الميكانيكية', fr: 'ex: Génie Mécanique', en: 'e.g. Mechanical Engineering' },
  john_doe_example: { ar: 'مثال: محمد علي', fr: 'ex: Jean Dupont', en: 'e.g. John Doe' },
  student_id_example: { ar: 'مثال: 20230001', fr: 'ex: 20230001', en: 'e.g. 20230001' },
  send_account_details_title: { ar: 'إرسال بيانات الحساب', fr: 'Envoyer les détails du compte', en: 'Send Account Details' },
  confirm_add_entry_desc: { ar: 'هل أنت متأكد من إضافة هذا الإدخال إلى الجدول؟', fr: 'Êtes-vous sûr de vouloir ajouter cette entrée à l\'emploi du temps ?', en: 'Are you sure you want to add this entry to the schedule?' },
  section_details: { ar: 'تفاصيل القسم', fr: 'Détails de la section', en: 'Section Details' },
  save_stats: { ar: 'حفظ الإحصائيات', fr: 'Enregistrer les statistiques', en: 'Save Statistics' },
  export_word: { ar: 'تصدير Word', fr: 'Exporter Word', en: 'Export Word' },
  export_excel: { ar: 'تصدير Excel', fr: 'Exporter Excel', en: 'Export Excel' },
  export_pdf: { ar: 'تصدير PDF', fr: 'Exporter PDF', en: 'Export PDF' },
  specialties_per_phase: { ar: 'التخصصات حسب الطور', fr: 'Spécialités par phase', en: 'Specialties per Phase' },
  modules_per_level_specialty: { ar: 'المقاييس حسب المستوى والتخصص', fr: 'Modules par niveau et spécialité', en: 'Modules per Level & Specialty' },
  students_per_level: { ar: 'الطلبة حسب المستوى', fr: 'Étudiants par niveau', en: 'Students per Level' },
  admin_actions_seed: { ar: 'إجراءات المسؤول: ملء قاعدة البيانات بالتخصصات والمقاييس الجديدة.', fr: 'Actions Admin : Remplir la base de données avec de nouvelles spécialités et modules.', en: 'Admin Actions: Populate database with new specialties and modules.' },
  seed_database: { ar: 'ملء قاعدة البيانات', fr: 'Remplir la base de données', en: 'Seed Database' },
  confirm_seed: { ar: 'تأكيد الملء', fr: 'Confirmer le remplissage', en: 'Confirm Seed' },
  seed_warning: { ar: 'تحذير: سيؤدي هذا إلى حذف جميع التخصصات والمستويات والمقاييس الحالية.', fr: 'Attention : cela supprimera toutes les spécialités, niveaux et modules existants.', en: 'Warning: This will delete all existing specialties, levels, and modules.' },
  seeding: { ar: 'جاري الملء...', fr: 'Remplissage en cours...', en: 'Seeding...' },
  processing: { ar: 'جاري المعالجة...', fr: 'Traitement en cours...', en: 'Processing...' },
  cours: { ar: 'دروس', fr: 'Cours', en: 'Cours' },
  td: { ar: 'أعمال موجهة', fr: 'TD', en: 'TD' },
  tp: { ar: 'أعمال تطبيقية', fr: 'TP', en: 'TP' },
  yes: { ar: 'نعم', fr: 'Oui', en: 'Yes' },
  no: { ar: 'لا', fr: 'Non', en: 'No' },
  auto: { ar: 'تلقائي', fr: 'Auto', en: 'Auto' },
  import_completed: { ar: 'اكتمل الاستيراد!', fr: 'Importation terminée !', en: 'Import completed!' },
  import_completed_skip_duplicates: { ar: 'اكتمل الاستيراد! تم تجاهل التكرارات.', fr: 'Importation terminée ! Les doublons ont été ignorés.', en: 'Import completed! Duplicates were skipped.' },
  import_failed: { ar: 'فشل الاستيراد.', fr: 'L\'importation a échoué.', en: 'Import failed.' },
  bulk_import: { ar: 'استيراد جماعي', fr: 'Importation en masse', en: 'Bulk Import' },
  importing: { ar: 'جاري الاستيراد...', fr: 'Importation en cours...', en: 'Importing...' },
  teacher_type: { ar: 'نوع الأستاذ', fr: 'Type d\'enseignant', en: 'Teacher Type' },
  permanent_internal: { ar: 'دائم (قسم الميكانيك)', fr: 'Permanent (Dép. Mécanique)', en: 'Permanent (Mechanical Dept)' },
  permanent_external: { ar: 'دائم (قسم آخر)', fr: 'Permanent (Autre dép.)', en: 'Permanent (Other Dept)' },
  temporary: { ar: 'مؤقت', fr: 'Vacataire', en: 'Temporary' },
  department: { ar: 'القسم', fr: 'Département', en: 'Department' },
  rank: { ar: 'الرتبة', fr: 'Grade', en: 'Rank' },
  select_rank: { ar: 'اختر الرتبة', fr: 'Sélectionner le grade', en: 'Select Rank' },
  appointment_date: { ar: 'تاريخ التعيين', fr: 'Date de nomination', en: 'Appointment Date' },
  appointment_duration: { ar: 'المدة: 3 سنوات، قابلة للتجديد مرة واحدة.', fr: 'Durée : 3 ans, renouvelable une fois.', en: 'Duration: 3 years, renewable once.' },
  renewed_appointment: { ar: 'تعيين مجدد', fr: 'Nomination renouvelée', en: 'Renewed Appointment' },
  under_1275: { ar: 'ضمن القرار 1275', fr: 'Sous décision 1275', en: 'Under Decision 1275' },
  view_account: { ar: 'رؤية الحساب', fr: 'Voir le compte', en: 'View Account' },
  account_created_success: { ar: 'تم إنشاء الحساب بنجاح', fr: 'Compte créé avec succès', en: 'Account Created Successfully' },
  credentials_for: { ar: 'بيانات الاعتماد لـ', fr: 'Identifiants pour', en: 'Credentials for' },
  username_email: { ar: 'اسم المستخدم / البريد الإلكتروني', fr: 'Nom d\'utilisateur / Email', en: 'Username / Email' },
  password: { ar: 'كلمة المرور', fr: 'Mot de passe', en: 'Password' },
  copy: { ar: 'نسخ', fr: 'Copier', en: 'Copy' },
  whatsapp_message: { 
    ar: 'مرحباً {name}،\n\nبيانات الدخول الخاصة بك:\nالبريد الإلكتروني: {email}\nكلمة المرور: {password}\n\nرابط التطبيق:\n{url}', 
    fr: 'Bonjour {name},\n\nVos identifiants de connexion :\nEmail : {email}\nMot de passe : {password}\n\nLien de l\'application :\n{url}', 
    en: 'Hello {name},\n\nYour login credentials:\nEmail: {email}\nPassword: {password}\n\nApp Link:\n{url}' 
  },
  send_to_email: { ar: 'إرسال إلى البريد الإلكتروني', fr: 'Envoyer par email', en: 'Send to Email' },
  expired: { ar: 'منتهي', fr: 'Expiré', en: 'Expired' },
  expiring_soon: { ar: 'تنتهي صلاحيته قريبًا', fr: 'Expire bientôt', en: 'Expiring Soon' },
  active: { ar: 'نشط', fr: 'Actif', en: 'Active' },
  expires: { ar: 'تنتهي الصلاحية:', fr: 'Expire le :', en: 'Expires:' },
  renewed_once: { ar: 'جدد مرة واحدة', fr: 'Renouvelé une fois', en: 'Renewed Once' },
  assistant: { ar: 'أستاذ مساعد', fr: 'Assistant', en: 'Assistant' },
  lecturer: { ar: 'أستاذ محاضر', fr: 'Maître de conférences', en: 'Lecturer' },
  professor: { ar: 'أستاذ تعليم عالي', fr: 'Professeur', en: 'Professor' },
  temporary_staff: { ar: 'الأساتذة المؤقتون', fr: 'Enseignants vacataires', en: 'Temporary Staff' },
  workload: { ar: 'حجم العمل', fr: 'Charge de travail', en: 'Workload' },
  first_year_teaching: { ar: 'تدريس السنة الأولى', fr: 'Enseignement 1ère année', en: '1st Year Teaching' },
  english_taught: { ar: 'دروس بالإنجليزية', fr: 'Cours en anglais', en: 'English Taught' },
  remote_lessons: { ar: 'دروس عن بعد', fr: 'Cours à distance', en: 'Remote Lessons' },
  reports: { ar: 'التقارير', fr: 'Rapports', en: 'Reports' },
  settings: { ar: 'الإعدادات', fr: 'Paramètres', en: 'Settings' },
  settings_desc: { ar: 'إدارة حسابك وتفضيلات التطبيق', fr: 'Gérez votre compte et les préférences de l\'application', en: 'Manage your account and application preferences' },
  profile: { ar: 'الملف الشخصي', fr: 'Profil', en: 'Profile' },
  language: { ar: 'اللغة', fr: 'Langue', en: 'Language' },
  admin_controls: { ar: 'تحكم المسؤول', fr: 'Contrôles administrateur', en: 'Admin Controls' },
  admin_settings_info: { ar: 'إعدادات التطبيق العامة تدار من هنا. المزيد من الضوابط قريباً.', fr: 'Les paramètres globaux de l\'application sont gérés ici. Plus de contrôles bientôt.', en: 'Global application settings are managed here. More controls coming soon.' },
  name: { ar: 'الاسم', fr: 'Nom', en: 'Name' },
  email: { ar: 'البريد الإلكتروني', fr: 'Email', en: 'Email' },
  role: { ar: 'الدور', fr: 'Rôle', en: 'Role' },
  logout: { ar: 'تسجيل الخروج', fr: 'Déconnexion', en: 'Logout' },
  login: { ar: 'تسجيل الدخول', fr: 'Connexion', en: 'Login' },
  welcome: { ar: 'مرحباً بك', fr: 'Bienvenue', en: 'Welcome' },
  admin: { ar: 'رئيس القسم', fr: 'Chef de département', en: 'Head of Department' },
  vice_admin: { ar: 'نائب رئيس القسم', fr: 'Vice-chef de département', en: 'Deputy Head of Department' },
  manager: { ar: 'مسؤول تخصص', fr: 'Responsable de spécialité', en: 'Specialty Manager' },
  teacher: { ar: 'أستاذ', fr: 'Enseignant', en: 'Teacher' },
  calendar_setup: { ar: 'إعداد الرزنامة', fr: 'Configuration du calendrier', en: 'Calendar Setup' },
  semester_start: { ar: 'بداية السداسي', fr: 'Début du semestre', en: 'Semester Start' },
  semester_end: { ar: 'نهاية السداسي', fr: 'Fin du semestre', en: 'Semester End' },
  semester1: { ar: 'السداسي الأول', fr: 'Semestre 1', en: 'Semester 1' },
  semester2: { ar: 'السداسي الثاني', fr: 'Semestre 2', en: 'Semester 2' },
  holidays: { ar: 'الأيام المستثناة', fr: 'Jours exclus', en: 'Excluded Days' },
  excluded_days: { ar: 'الأيام المستثناة', fr: 'Jours exclus', en: 'Excluded Days' },
  save_calendar: { ar: 'حفظ الرزنامة', fr: 'Enregistrer le calendrier', en: 'Save Calendar' },
  generate_sessions_title: { ar: 'توليد الحصص تلقائياً', fr: 'Génération automatique des séances', en: 'Auto-generate Sessions' },
  generate_sessions_desc: { ar: 'سيقوم النظام بإنشاء جميع الحصص بناءً على الجدول والرزنامة.', fr: 'Le système créera toutes les séances basées sur l\'emploi du temps et le calendrier.', en: 'The system will create all sessions based on the schedule and calendar.' },
  generate_sessions_btn: { ar: 'توليد الحصص الآن', fr: 'Générer les séances maintenant', en: 'Generate Sessions Now' },
  search_sessions: { ar: 'بحث عن حصة...', fr: 'Rechercher une séance...', en: 'Search sessions...' },
  taught: { ar: 'تم التدريس', fr: 'Enseigné', en: 'Taught' },
  missed: { ar: 'لم يتم التدريس', fr: 'Non enseigné', en: 'Missed' },
  problem: { ar: 'مشكل', fr: 'Problème', en: 'Problem' },
  enter_problem_type: { ar: 'أدخل نوع المشكلة', fr: 'Entrez le type de problème', en: 'Enter problem type' },
  no_sessions_found: { ar: 'لا توجد حصص حالياً', fr: 'Aucune séance trouvée', en: 'No sessions found' },
  recent_sessions: { ar: 'الحصص الأخيرة', fr: 'Séances récentes', en: 'Recent Sessions' },
  active_projects: { ar: 'مشاريع التخرج النشطة', fr: 'Projets PFE actifs', en: 'Active PFE Projects' },
  taught_sessions: { ar: 'حصص منجزة', fr: 'Séances effectuées', en: 'Taught Sessions' },
  missed_sessions: { ar: 'حصص ضائعة', fr: 'Séances manquées', en: 'Missed Sessions' },
  problems: { ar: 'مشاكل مسجلة', fr: 'Problèmes signalés', en: 'Reported Problems' },
  delete_all: { ar: 'حذف الكل', fr: 'Tout supprimer', en: 'Delete All' },
  confirm_delete_all: { ar: 'تأكيد حذف جميع الحصص؟', fr: 'Confirmer la suppression de toutes les séances ?', en: 'Confirm Delete All Sessions?' },
  confirm_delete_all_desc: { ar: 'هل أنت متأكد من حذف جميع الحصص المفلترة؟ لا يمكن التراجع عن هذا الإجراء.', fr: 'Êtes-vous sûr de vouloir supprimer toutes les séances filtrées ? Cette action ne peut pas être annulée.', en: 'Are you sure you want to delete all filtered sessions? This action cannot be undone.' },
  confirm_delete: { ar: 'هل أنت متأكد من الحذف؟', fr: 'Êtes-vous sûr de vouloir supprimer ?', en: 'Are you sure you want to delete?' },
  confirm_delete_desc_1: { ar: 'هل أنت متأكد من حذف', fr: 'Êtes-vous sûr de vouloir supprimer', en: 'Are you sure you want to delete the' },
  confirm_delete_desc_2: { ar: 'سيؤدي هذا أيضًا إلى حذف جميع البيانات المرتبطة.', fr: 'Cela supprimera également toutes les données associées.', en: 'This will also delete all associated data.' },
  action_cannot_be_undone: { ar: 'لا يمكن التراجع عن هذا الإجراء.', fr: 'Cette action ne peut pas être annulée.', en: 'This action cannot be undone.' },
  edit_teacher: { ar: 'تعديل بيانات الأستاذ', fr: 'Modifier l\'enseignant', en: 'Edit Teacher' },
  add_teacher: { ar: 'إضافة أستاذ', fr: 'Ajouter un enseignant', en: 'Add Teacher' },
  full_name: { ar: 'الاسم الكامل', fr: 'Nom complet', en: 'Full Name' },
  holiday_name: { ar: 'اسم العطلة', fr: 'Nom de la fête', en: 'Holiday Name' },
  national: { ar: 'عطلة رسمية', fr: 'Vacance officielle', en: 'Official Holiday' },
  religious: { ar: 'عيد ديني', fr: 'Fête religieuse', en: 'Religious Holiday' },
  break: { ar: 'عطلة جامعية', fr: 'Vacances universitaires', en: 'University Break' },
  pedagogical: { ar: 'توقف بيداغوجي', fr: 'Arrêt pédagogique', en: 'Pedagogical Stop' },
  exam: { ar: 'فترة امتحانات', fr: 'Période d\'examens', en: 'Exam Period' },
  exceptional: { ar: 'يوم استثنائي', fr: 'Jour exceptionnel', en: 'Exceptional Day' },
  other_holiday: { ar: 'سبب آخر', fr: 'Autre raison', en: 'Other Reason' },
  add_holiday: { ar: 'إضافة يوم مستثنى', fr: 'Ajouter un jour exclu', en: 'Add Excluded Day' },
  import_schedule_first: { ar: 'يرجى استيراد جدول السداسي أولاً', fr: 'Veuillez d\'abord importer un emploi du temps', en: 'Please import a semester schedule first' },
  sessions_generated_success: { ar: 'تم توليد الحصص بنجاح!', fr: 'Séances générées avec succès !', en: 'Sessions generated successfully!' },
  error_generating_sessions: { ar: 'خطأ في توليد الحصص', fr: 'Erreur lors de la génération des séances', en: 'Error generating sessions' },
  add_level: { ar: 'إضافة سنة/مستوى', fr: 'Ajouter un niveau/année', en: 'Add Level/Year' },
  level_name: { ar: 'اسم المستوى', fr: 'Nom du niveau', en: 'Level Name' },
  student_count: { ar: 'عدد الطلبة', fr: 'Nombre d\'étudiants', en: 'Student Count' },
  level_exists_error: { ar: 'هذا المستوى موجود بالفعل لهذا التخصص.', fr: 'Ce niveau existe déjà pour cette spécialité.', en: 'This level already exists for this specialty.' },
  level_added_success: { ar: 'تم إضافة المستوى بنجاح', fr: 'Niveau ajouté avec succès', en: 'Level added successfully' },
  specialty_name: { ar: 'اسم التخصص', fr: 'Nom de la spécialité', en: 'Specialty Name' },
  levels: { ar: 'السنوات/المستويات', fr: 'Niveaux/Années', en: 'Levels/Years' },
  // Session Problems
  group_absence: { ar: 'غياب جماعي', fr: 'Absence collective', en: 'Group Absence' },
  majority_absence: { ar: 'غياب أغلب الطلبة', fr: 'Absence de la majorité', en: 'Majority Absence' },
  lack_of_means: { ar: 'نقص الوسائل', fr: 'Manque de moyens', en: 'Lack of Means' },
  room_problem: { ar: 'مشكل قاعة', fr: 'Problème de salle', en: 'Room Problem' },
  student_delay: { ar: 'تأخر الطلبة', fr: 'Retard des étudiants', en: 'Student Delay' },
  teacher_delay: { ar: 'تأخر الأستاذ', fr: 'Retard de l\'enseignant', en: 'Teacher Delay' },
  organizational: { ar: 'مشكل تنظيمي', fr: 'Problème organisationnel', en: 'Organizational' },
  other_session: { ar: 'مشكل آخر', fr: 'Autre problème', en: 'Other' },
  // Project Stages
  start: { ar: 'بداية العمل', fr: 'Début du travail', en: 'Work Start' },
  references: { ar: 'جمع المراجع', fr: 'Collecte de références', en: 'References Collection' },
  theory: { ar: 'الدراسة النظرية', fr: 'Étude théorique', en: 'Theoretical Study' },
  practical: { ar: 'العمل التطبيقي', fr: 'Travail pratique', en: 'Practical Work' },
  writing: { ar: 'كتابة التقرير', fr: 'Rédaction du rapport', en: 'Report Writing' },
  ready: { ar: 'جاهز للمناقشة', fr: 'Prêt pour la soutenance', en: 'Ready for Defense' },
  // Supervision Problems
  no_response: { ar: 'الطالب لا يتجاوب', fr: 'L\'étudiant ne répond pas', en: 'No Response' },
  absence: { ar: 'غياب الطالب', fr: 'Absence de l\'étudiant', en: 'Student Absence' },
  delay: { ar: 'تأخر في العمل', fr: 'Retard dans le travail', en: 'Work Delay' },
  technical: { ar: 'مشكل تقني', fr: 'Problème technique', en: 'Technical Problem' },
  data_lack: { ar: 'نقص معطيات', fr: 'Manque de données', en: 'Lack of Data' },
  other_supervision: { ar: 'مشكل آخر', fr: 'Autre problème', en: 'Other' },
  report_problem: { ar: 'تبليغ عن مشكل', fr: 'Signaler un problème', en: 'Report Problem' },
  reported_problems: { ar: 'المشاكل المسجلة', fr: 'Problèmes signalés', en: 'Reported Problems' },
  // Abandonment Reasons
  no_commitment: { ar: 'عدم التزام الطالب', fr: 'Manque d\'engagement', en: 'No Commitment' },
  repeated_absence: { ar: 'غياب متكرر', fr: 'Absence répétée', en: 'Repeated Absence' },
  interruption: { ar: 'انقطاع الطالب', fr: 'Interruption de l\'étudiant', en: 'Student Interruption' },
  work_pressure: { ar: 'ضغط العمل', fr: 'Pression de travail', en: 'Work Pressure' },
  administrative: { ar: 'سبب إداري', fr: 'Raison administrative', en: 'Administrative' },
  other_abandonment: { ar: 'سبب آخر', fr: 'Autre raison', en: 'Other' },
  abandon_supervision: { ar: 'طلب التخلي عن التأطير', fr: 'Demande d\'abandon d\'encadrement', en: 'Abandon Supervision' },
  abandonment_request: { ar: 'طلب التخلي', fr: 'Demande d\'abandon', en: 'Abandonment Request' },
  // Statuses
  available: { ar: 'متاح', fr: 'Disponible', en: 'Available' },
  reserved: { ar: 'محجوز مؤقتاً', fr: 'Réservé temporairement', en: 'Temporarily Reserved' },
  approved: { ar: 'معتمد', fr: 'Approuvé', en: 'Approved' },
  cancelled: { ar: 'ملغاة', fr: 'Annulé', en: 'Cancelled' },
  internship: { ar: 'فترة تربص', fr: 'Période de stage', en: 'Internship' },
  sick: { ar: 'مرض', fr: 'Maladie', en: 'Sick' },
  // Project
  propose_project: { ar: 'اقتراح مشروع', fr: 'Proposer un projet', en: 'Propose Project' },
  edit_project: { ar: 'تعديل المشروع', fr: 'Modifier le projet', en: 'Edit Project' },
  distribute_to_students: { ar: 'توزيع على الطلبة', fr: 'Distribuer aux étudiants', en: 'Distribute to Students' },
  student_names_comma: { ar: 'أسماء الطلبة (مفصولة بفاصلة)', fr: 'Noms des étudiants (séparés par virgule)', en: 'Student Names (comma separated)' },
  distributed: { ar: 'تم التوزيع', fr: 'Distribué', en: 'Distributed' },
  not_distributed: { ar: 'لم يوزع بعد', fr: 'Non distribué', en: 'Not distributed' },
  project_title: { ar: 'عنوان المشروع', fr: 'Titre du projet', en: 'Project Title' },
  project_description: { ar: 'وصف المشروع', fr: 'Description du projet', en: 'Project Description' },
  description: { ar: 'الوصف', fr: 'Description', en: 'Description' },
  keywords_comma: { ar: 'الكلمات المفتاحية (مفصولة بفاصلة)', fr: 'Mots-clés (séparés par virgule)', en: 'Keywords (comma separated)' },
  update_progress: { ar: 'تحديث التقدم', fr: 'Mettre à jour la progression', en: 'Update Progress' },
  progress: { ar: 'التقدم', fr: 'Progression', en: 'Progress' },
  accept: { ar: 'قبول', fr: 'Accepter', en: 'Accept' },
  reject: { ar: 'رفض', fr: 'Refuser', en: 'Reject' },
  edit: { ar: 'تعديل', fr: 'Modifier', en: 'Edit' },
  distribute: { ar: 'توزيع', fr: 'Distribuer', en: 'Distribute' },
  // Specialties & Levels
  license: { ar: 'ليسانس', fr: 'Licence', en: 'License' },
  master: { ar: 'ماستر', fr: 'Master', en: 'Master' },
  engineers: { ar: 'مهندسين', fr: 'Ingénieurs', en: 'Engineers' },
  lmd_field: { ar: 'ميدان LMD', fr: 'Domaine LMD', en: 'LMD Field' },
  engineers_field: { ar: 'ميدان المهندسين', fr: 'Domaine Ingénieurs', en: 'Engineers Field' },
  send_account_details: { ar: 'إرسال بيانات الحساب؟', fr: 'Envoyer les détails du compte ?', en: 'Send account details?' },
  managed_specialty: { ar: 'التخصص المسير', fr: 'Spécialité gérée', en: 'Managed Specialty' },
  managed_phase: { ar: 'الطور المسير', fr: 'Phase gérée', en: 'Managed Phase' },
  select_specialty: { ar: 'اختر التخصص', fr: 'Sélectionner la spécialité', en: 'Select Specialty' },
  select_phase: { ar: 'اختر الطور', fr: 'Sélectionner la phase', en: 'Select Phase' },
  generate_account: { ar: 'توليد حساب', fr: 'Générer un compte', en: 'Generate Account' },
  regenerate_password: { ar: 'إعادة توليد كلمة المرور', fr: 'Régénérer le mot de passe', en: 'Regenerate Password' },
  import_schedule: { ar: 'استيراد الجدول', fr: 'Importer l\'emploi du temps', en: 'Import Schedule' },
  semester_schedule: { ar: 'جدول السداسي', fr: 'Emploi du temps du semestre', en: 'Semester Schedule' },
  invigilation_schedule: { ar: 'جدول الحراسة', fr: 'Planning de surveillance', en: 'Invigilation Schedule' },
  remedial_invigilation_schedule: { ar: 'جدول الحراسة الاستدراكية', fr: 'Planning de surveillance de rattrapage', en: 'Remedial Invigilation Schedule' },
  smart_ai_extract: { ar: 'استخراج ذكي بالذكاء الاصطناعي', fr: 'Extraction intelligente par IA', en: 'Smart AI Extract' },
  preview_data: { ar: 'معاينة البيانات', fr: 'Aperçu des données', en: 'Preview Data' },
  save_schedule: { ar: 'حفظ الجدول', fr: 'Enregistrer l\'emploi du temps', en: 'Save Schedule' },
  download: { ar: 'تحميل', fr: 'Télécharger', en: 'Download' },
  my_schedules: { ar: 'جداولي', fr: 'Mes emplois du temps', en: 'My Schedules' },
  add_session: { ar: 'إضافة حصة', fr: 'Ajouter une séance', en: 'Add Session' },
  taught_with_problem: { ar: 'تم التدريس مع مشكل', fr: 'Enseigné avec problème', en: 'Taught with Problem' },
  internship_period: { ar: 'فترة تربص', fr: 'Période de stage', en: 'Internship Period' },
  sick_leave: { ar: 'عطلة مرضية', fr: 'Congé maladie', en: 'Sick Leave' },
  add_module: { ar: 'إضافة مقياس', fr: 'Ajouter un module', en: 'Add Module' },
  edit_module: { ar: 'تعديل المقياس', fr: 'Modifier le module', en: 'Edit Module' },
  module_name: { ar: 'اسم المقياس', fr: 'Nom du module', en: 'Module Name' },
  module_exists_error: { ar: 'هذا المقياس موجود بالفعل لهذا المستوى والسداسي.', fr: 'Ce module existe déjà pour ce niveau et ce semestre.', en: 'This module already exists for this level and semester.' },
  module_added_success: { ar: 'تم إضافة المقياس بنجاح', fr: 'Module ajouté avec succès', en: 'Module added successfully' },
  module_updated_success: { ar: 'تم تحديث المقياس بنجاح', fr: 'Module mis à jour avec succès', en: 'Module updated successfully' },
  copy_link: { ar: 'نسخ الرابط', fr: 'Copier le lien', en: 'Copy Link' },
  link_copied: { ar: 'تم نسخ الرابط بنجاح!', fr: 'Lien copié avec succès !', en: 'Link copied successfully!' },
  semester: { ar: 'السداسي', fr: 'Semestre', en: 'Semester' },
  semester_1: { ar: 'السداسي الأول', fr: 'Semestre 1', en: 'Semester 1' },
  semester_2: { ar: 'السداسي الثاني', fr: 'Semestre 2', en: 'Semester 2' },
  no_modules: { ar: 'لا توجد مقاييس', fr: 'Aucun module', en: 'No modules' },
  select_status: { ar: 'اختر الحالة', fr: 'Sélectionner l\'état', en: 'Select Status' },
  delete: { ar: 'حذف', fr: 'Supprimer', en: 'Delete' },
  add_project: { ar: 'إضافة مشروع', fr: 'Ajouter un projet', en: 'Add Project' },
  add_specialty: { ar: 'إضافة تخصص', fr: 'Ajouter une spécialité', en: 'Add Specialty' },
  specialty_exists_error: { ar: 'هذا التخصص موجود بالفعل لهذا النوع من المستويات.', fr: 'Cette spécialité existe déjà pour ce type de niveau.', en: 'This specialty already exists for this level type.' },
  specialty_added_success: { ar: 'تم إضافة التخصص بنجاح', fr: 'Spécialité ajoutée avec succès', en: 'Specialty added successfully' },
  field_placeholder: { ar: 'الميدان (مثال: LMD، مهندسين)', fr: 'Domaine (ex: LMD, Ingénieurs)', en: 'Field (e.g. LMD, Engineers)' },
  resetting_database: { ar: 'جاري إعادة تعيين قاعدة البيانات...', fr: 'Réinitialisation de la base de données...', en: 'Resetting database...' },
  database_reset_success: { ar: 'تم إعادة تعيين قاعدة البيانات بنجاح!', fr: 'Base de données réinitialisée avec succès !', en: 'Database reset successfully!' },
  reset_failed: { ar: 'فشلت إعادة التعيين.', fr: 'La réinitialisation a échoué.', en: 'Reset failed.' },
  reset_now: { ar: 'إعادة التعيين الآن', fr: 'Réinitialiser maintenant', en: 'Reset Now' },
  reset_to_english: { ar: 'إعادة التعيين إلى الإنجليزية', fr: 'Réinitialiser en anglais', en: 'Reset to English' },
  reset_to_english_title: { ar: 'إعادة تعيين جميع المستويات إلى الإنجليزية', fr: 'Réinitialiser tous les niveaux en anglais', en: 'Reset all levels to English' },
  reset_database_confirm_title: { ar: 'إعادة تعيين قاعدة البيانات؟', fr: 'Réinitialiser la base de données ?', en: 'Reset Database?' },
  reset_database_confirm_desc: { ar: 'سيؤدي هذا إلى حذف جميع التخصصات والمستويات والمقاييس الحالية وإعادة تعيينها إلى الهيكل الإنجليزي الجديد. لا يمكن التراجع عن هذا الإجراء.', fr: 'Cela supprimera toutes les spécialités, niveaux et modules actuels et les réinitialisera au nouveau format anglais. Cette action ne peut pas être annulée.', en: 'This will delete all current specialties, levels, and modules and reset them to the new English structure. This action cannot be undone.' },
  yes_reset: { ar: 'نعم، أعد التعيين', fr: 'Oui, réinitialiser', en: 'Yes, Reset' },
  arabic_levels_warning: { ar: 'بعض المستويات لا تزال باللغة العربية. انقر فوق "إعادة التعيين إلى الإنجليزية" لتحديث هيكل قاعدة البيانات الخاصة بك إلى التنسيق الإنجليزي الجديد.', fr: 'Certains niveaux sont encore en arabe. Cliquez sur "Réinitialiser en anglais" pour mettre à jour la structure de votre base de données vers le nouveau format anglais.', en: 'Some levels are still in Arabic. Click "Reset to English" to update your database structure to the new English format.' },
  deleting: { ar: 'جاري الحذف', fr: 'Suppression en cours', en: 'Deleting' },
  deleted_successfully: { ar: 'تم الحذف بنجاح', fr: 'supprimé avec succès', en: 'deleted successfully' },
  delete_failed: { ar: 'فشل الحذف.', fr: 'La suppression a échoué.', en: 'Delete failed.' },
  add: { ar: 'إضافة', fr: 'Ajouter', en: 'Add' },
  save: { ar: 'حفظ', fr: 'Enregistrer', en: 'Save' },
  cancel: { ar: 'إلغاء', fr: 'Annuler', en: 'Cancel' },
  module: { ar: 'المقياس', fr: 'Module', en: 'Module' },
  specialty: { ar: 'التخصص', fr: 'Spécialité', en: 'Specialty' },
  level: { ar: 'المستوى', fr: 'Niveau', en: 'Level' },
  room: { ar: 'القاعة', fr: 'Salle', en: 'Room' },
  group: { ar: 'الفوج', fr: 'Groupe', en: 'Group' },
  type: { ar: 'النوع', fr: 'Type', en: 'Type' },
  pending: { ar: 'قيد الانتظار', fr: 'En attente', en: 'Pending' },
  view: { ar: 'عرض', fr: 'Voir', en: 'View' },
  view_all_specialties: { ar: 'عرض كل التخصصات', fr: 'Voir toutes les spécialités', en: 'View all specialties' },
  close: { ar: 'إغلاق', fr: 'Fermer', en: 'Close' },
  semester_schedule_title: { ar: 'جدول السداسي', fr: 'Emploi du temps du semestre', en: 'Semester Schedule' },
  normal_exam_schedule: { ar: 'جدول الامتحانات العادية', fr: 'Planning des examens normaux', en: 'Normal Exam Schedule' },
  remedial_exam_schedule: { ar: 'جدول الامتحانات الاستدراكية', fr: 'Planning des examens de rattrapage', en: 'Remedial Exam Schedule' },
  cycle: { ar: 'الطور', fr: 'Cycle', en: 'Cycle' },
  branch: { ar: 'الفرع/الشعبة', fr: 'Branche/Section', en: 'Branch/Section' },
  session_label: { ar: 'حصة', fr: 'Séance', en: 'Session' },
  start_time_label: { ar: 'بداية', fr: 'Début', en: 'Start' },
  end_time_label: { ar: 'نهاية', fr: 'Fin', en: 'End' },
  online: { ar: 'عن بعد', fr: 'À distance', en: 'Online' },
  in_english: { ar: 'باللغة الإنجليزية', fr: 'En anglais', en: 'In English' },
  exam_management: { ar: 'تسيير الامتحانات', fr: 'Gestion des examens', en: 'Exam Management' },
  confirm_add_exam_entry: { ar: 'هل أنت متأكد من إضافة هذا الامتحان؟', fr: 'Êtes-vous sûr de vouloir ajouter cet examen ?', en: 'Are you sure you want to add this exam?' },
  exam_name: { ar: 'اسم الامتحان', fr: 'Nom de l\'examen', en: 'Exam Name' },
  academic_year: { ar: 'السنة الدراسية', fr: 'Année académique', en: 'Academic Year' },
  remedial_checkbox: { ar: 'امتحان مستدرك', fr: 'Examen de rattrapage', en: 'Remedial Exam' },
  deploy_exam: { ar: 'نشر إدخال الامتحان', fr: 'Déployer l\'entrée d\'examen', en: 'Deploy Exam Entry' },
  failed_students_count: { ar: 'عدد الطلبة الراسبين', fr: 'Nombre d\'étudiants échoués', en: 'Number of Failed Students' },
  normal_exams_list: { ar: 'الامتحانات العادية', fr: 'Examens normaux', en: 'Normal Exams' },
  remedial_exams_list: { ar: 'الامتحانات الاستدراكية', fr: 'Examens de rattrapage', en: 'Remedial Exams' },
  select_program: { ar: 'اختر الطور', fr: 'Sélectionner le programme', en: 'Select Program' },
  select_subject: { ar: 'اختر المقياس', fr: 'Sélectionner le module', en: 'Select Subject' },
  select_branch: { ar: 'اختر الفرع', fr: 'Sélectionner la branche', en: 'Select Branch' },
  add_entry: { ar: 'إضافة حصة', fr: 'Ajouter une séance', en: 'Add Session' },
  edit_entry: { ar: 'تعديل الحصة', fr: 'Modifier la séance', en: 'Edit Session' },
  confirm_add_entry: { ar: 'هل أنت متأكد من إضافة هذا الإدخال؟', fr: 'Êtes-vous sûr de vouloir ajouter cette entrée ?', en: 'Are you sure you want to add this entry?' },
  update: { ar: 'تحديث', fr: 'Mettre à jour', en: 'Update' },
  all_specialties: { ar: 'كل التخصصات', fr: 'Toutes les spécialités', en: 'All Specialties' },
  all_levels: { ar: 'كل المستويات', fr: 'Tous les niveaux', en: 'All Levels' },
  confirm_send_email: { ar: 'هل تريد إرسال الجدول إلى جميع الأساتذة المعنيين؟', fr: 'Voulez-vous envoyer l\'emploi du temps à tous les enseignants concernés ?', en: 'Do you want to send the schedule to all concerned teachers?' },
  confirm_send_email_desc: { ar: 'سيتم إرسال نسخة من الجدول إلى البريد الإلكتروني لكل أستاذ معني.', fr: 'Une copie de l\'emploi du temps sera envoyée à l\'e-mail de chaque enseignant concerné.', en: 'A copy of the schedule will be sent to the email of each concerned teacher.' },
  confirm_send_personal_email_desc: { ar: 'هل تريد إرسال جدولك الشخصي إلى بريدك الإلكتروني؟', fr: 'Voulez-vous envoyer votre emploi du temps personnel à votre e-mail ?', en: 'Do you want to send your personal schedule to your email?' },
  all_notifications_sent: { ar: 'تم إرسال جميع الإشعارات بنجاح إلى الأساتذة المعنيين', fr: 'Toutes les notifications ont été envoyées avec succès aux enseignants concernés', en: 'All notifications sent successfully to concerned teachers' },
  notification_sent: { ar: 'تم إرسال الإشعار بنجاح', fr: 'Notification envoyée avec succès', en: 'Notification sent successfully' },
  sending_email: { ar: 'جاري الإرسال...', fr: 'Envoi en cours...', en: 'Sending...' },
  teaching_sessions: { ar: 'عدد حصص التدريس', fr: 'Nombre de séances d\'enseignement', en: 'Teaching Sessions' },
  invigilation_sessions: { ar: 'عدد حصص الحراسة', fr: 'Nombre de séances de surveillance', en: 'Invigilation Sessions' },
  supervision_sessions: { ar: 'عدد حصص التأطير', fr: 'Nombre de séances d\'encadrement', en: 'Supervision Sessions' },
  defense_confirmed: { ar: 'تم تأكيد المناقشة', fr: 'Soutenance confirmée', en: 'Defense Confirmed' },
  certificate_issued: { ar: 'تم إصدار الشهادة', fr: 'Certificat délivré', en: 'Certificate Issued' },
  certificate_type: { ar: 'نوع الشهادة', fr: 'Type de certificat', en: 'Certificate Type' },
  issued_at: { ar: 'تاريخ الإصدار', fr: 'Délivré le', en: 'Issued At' },
  refresh_app: { ar: 'تحديث التطبيق', fr: 'Actualiser l\'application', en: 'Refresh Application' },
  app_refreshed: { ar: 'تم تحديث التطبيق لجميع المستخدمين', fr: 'Application actualisée pour tous les utilisateurs', en: 'Application refreshed for all users' },
  no_emails_found: { ar: 'لم يتم العثور على عناوين بريد إلكتروني صالحة', fr: 'Aucune adresse e-mail valide trouvée', en: 'No valid email addresses found' },
  success: { ar: 'تم بنجاح', fr: 'Succès', en: 'Success' },
  error_occurred: { ar: 'حدث خطأ', fr: 'Une erreur est survenue', en: 'An error occurred' },
  no_schedule_found: { ar: 'لم يتم العثور على جدول', fr: 'Aucun emploi du temps trouvé', en: 'No schedule found' },
  normal_exam: { ar: 'امتحان عادي', fr: 'Examen Normal', en: 'Normal Exam' },
  remedial_exam: { ar: 'امتحان استدراكي', fr: 'Examen de Rattrapage', en: 'Remedial Exam' },
  hall_utilization: { ar: 'استغلال القاعة', fr: 'Utilisation des Salles', en: 'Hall Utilization' },
  temporary_teacher: { ar: 'أستاذ مؤقت', fr: 'Enseignant Vacataire', en: 'Temporary Teacher' },
  overtime_calculation: { ar: 'حساب الساعات الإضافية', fr: 'Calcul des Heures Supplémentaires', en: 'Overtime Calculation' },
  overtime_submission: { ar: 'تقديم الساعات الإضافية', fr: 'Soumission des Heures Supplémentaires', en: 'Overtime Submission' },
  external_hours: { ar: 'ساعات خارج القسم', fr: 'Heures hors département', en: 'External Hours' },
  internal_hours: { ar: 'ساعات داخل القسم', fr: 'Heures internes', en: 'Internal Hours' },
  submit_overtime: { ar: 'تقديم الساعات', fr: 'Soumettre les heures', en: 'Submit Hours' },
  approve: { ar: 'تأكيد', fr: 'Approuver', en: 'Approve' },
  pending_approval: { ar: 'في انتظار التأكيد', fr: 'En attente d\'approbation', en: 'Pending Approval' },
  approved_overtime_list: { ar: 'قائمة الساعات المعتمدة', fr: 'Liste des heures approuvées', en: 'Approved Overtime List' },
  confirmed_overtime_list: { ar: 'قائمة الساعات المؤكدة', fr: 'Liste des heures confirmées', en: 'Confirmed Overtime List' },
  download_approved_list: { ar: 'تحميل القائمة المعتمدة', fr: 'Télécharger la liste approuvée', en: 'Download Approved List' },
  rejection_reason: { ar: 'سبب الرفض', fr: 'Raison du refus', en: 'Rejection Reason' },
  certificates: { ar: 'الشهادات', fr: 'Certificats', en: 'Certificates' },
  teaching_certificate: { ar: 'شهادة تدريس', fr: 'Certificat d\'enseignement', en: 'Teaching Certificate' },
  supervision_certificate: { ar: 'شهادة تأطير ليسانس', fr: 'Certificat d\'encadrement Licence', en: 'Supervision Certificate' },
  issue_certificate: { ar: 'إصدار شهادة', fr: 'Délivrer un certificat', en: 'Issue Certificate' },
  clone_schedule: { ar: 'نسخ من سنة سابقة', fr: 'Copier d\'une année précédente', en: 'Clone from Previous Year' },
  select_academic_year: { ar: 'اختر السنة الدراسية', fr: 'Sélectionner l\'année académique', en: 'Select Academic Year' },
  overtime_alert: { ar: 'تنبيه: الساعات تتجاوز الحد المسموح به', fr: 'Alerte : Les heures dépassent la limite', en: 'Alert: Hours exceed limit' },
  display_name_ar: { ar: 'الاسم بالعربية', fr: 'Nom en arabe', en: 'Name in Arabic' },
  standard_workload: { ar: 'النصاب القانوني', fr: 'Charge Statutaire', en: 'Standard Workload' },
  total_hours: { ar: 'مجموع الساعات', fr: 'Total des Heures', en: 'Total Hours' },
  total_worked_hours: { ar: 'إجمالي ساعات العمل المنجزة', fr: 'Total des heures travaillées', en: 'Total Worked Hours' },
  overtime_hours: { ar: 'الساعات الإضافية', fr: 'Heures Supplémentaires', en: 'Overtime Hours' },
  download_template: { ar: 'تحميل النموذج', fr: 'Télécharger le Modèle', en: 'Download Template' },
  conflict_detected: { ar: 'تم اكتشاف تعارض', fr: 'Conflit détecté', en: 'Conflict Detected' },
  room_conflict: { ar: 'تعارض القاعة: القاعة محجوزة لحصة أخرى في هذا الوقت', fr: 'Conflit de salle : La salle est déjà occupée', en: 'Room Conflict: Room is already occupied' },
  teacher_conflict: { ar: 'تعارض الأستاذ: الأستاذ يدرس حصة أخرى في هذا الوقت', fr: 'Conflit d\'enseignant : L\'enseignant a une autre séance', en: 'Teacher Conflict: Teacher has another session' },
  group_conflict: { ar: 'تعارض الفوج: الفوج لديه حصة أخرى في هذا الوقت', fr: 'Conflit de groupe : Le groupe a une autre séance', en: 'Group Conflict: Group has another session' },
  duplicate_conflict: { ar: 'تكرار الحصة: هذه الحصة مسجلة بالفعل', fr: 'Séance en double : Cette séance est déjà enregistrée', en: 'Duplicate Session: This session is already recorded' },
  capacity_conflict: { ar: 'تعارض السعة: عدد الطلبة أكبر من سعة القاعة', fr: 'Conflit de capacité : Trop d\'étudiants pour cette salle', en: 'Capacity Conflict: Too many students for this room' },
  semester_level_conflict: { ar: 'تعارض السداسي أو المستوى: المقياس غير متوافق مع السداسي أو المستوى', fr: 'Conflit de semestre/niveau : Module incompatible', en: 'Semester/Level Conflict: Module incompatible' },
  lab_conflict: { ar: 'تعارض المورد الخاص: المخبر مستخدم في هذا الوقت', fr: 'Conflit de laboratoire : Labo déjà utilisé', en: 'Lab Conflict: Lab already in use' },
  already_scheduled: { ar: 'مجدول مسبقاً', fr: 'Déjà planifié', en: 'Already scheduled' },
  students: { ar: 'الطلبة', fr: 'Étudiants', en: 'Students' },
  student_management: { ar: 'إدارة الطلبة', fr: 'Gestion des étudiants', en: 'Student Management' },
  student_name: { ar: 'اسم الطالب', fr: 'Nom de l\'étudiant', en: 'Student Name' },
  registration_number: { ar: 'رقم التسجيل', fr: 'Matricule', en: 'Registration Number' },
  import_students: { ar: 'استيراد الطلبة', fr: 'Importer des étudiants', en: 'Import Students' },
  assigned: { ar: 'تم التعيين', fr: 'Assigné', en: 'Assigned' },
  unassigned: { ar: 'غير معين', fr: 'Non assigné', en: 'Unassigned' },
  fill_all_fields: { ar: 'يرجى ملء جميع الحقول المطلوبة', fr: 'Veuillez remplir tous les champs obligatoires', en: 'Please fill all required fields' },
  personal_schedule: { ar: 'جدول شخصي', fr: 'Emploi du temps personnel', en: 'Personal Schedule' },
  all_schedules: { ar: 'كل الجداول', fr: 'Tous les emplois du temps', en: 'All Schedules' },
  invigilators: { ar: 'المراقبون', fr: 'Surveillants', en: 'Invigilators' },
  send_email: { ar: 'إرسال عبر البريد', fr: 'Envoyer par e-mail', en: 'Send via Email' },
  switch_role: { ar: 'تبديل الدور', fr: 'Changer de rôle', en: 'Switch Role' },
  download_pdf: { ar: 'تحميل PDF', fr: 'Télécharger PDF', en: 'Download PDF' },
  no_entries_found: { ar: 'لم يتم العثور على أي إدخالات', fr: 'Aucune entrée trouvée', en: 'No entries found' },
  no_pending_approvals: { ar: 'لا توجد طلبات في انتظار التأكيد', fr: 'Aucune approbation en attente', en: 'No pending approvals' },
  rejected: { ar: 'مرفوض', fr: 'Refusé', en: 'Rejected' },
  requested: { ar: 'مطلوب', fr: 'Demandé', en: 'Requested' },
  prepared: { ar: 'جاهز', fr: 'Préparé', en: 'Prepared' },
  issued: { ar: 'صادر', fr: 'Délivré', en: 'Issued' },
  request_certificate: { ar: 'طلب شهادة', fr: 'Demander un certificat', en: 'Request Certificate' },
  prepare_certificate: { ar: 'إعداد الشهادة', fr: 'Préparer le certificat', en: 'Prepare Certificate' },
  edit_certificate: { ar: 'تعديل الشهادة', fr: 'Modifier le certificat', en: 'Edit Certificate' },
  active_account: { ar: 'حساب مفعل', fr: 'Compte actif', en: 'Active Account' },
  inactive_account: { ar: 'حساب موقوف', fr: 'Compte inactif', en: 'Inactive Account' },
  monthly_hours: { ar: 'الساعات الشهرية', fr: 'Heures mensuelles', en: 'Monthly Hours' },
  legal_threshold: { ar: 'النصاب القانوني', fr: 'Seuil légal', en: 'Legal Threshold' },
  upload_logo: { ar: 'تحميل الشعار', fr: 'Télécharger le logo', en: 'Upload Logo' },
  september: { ar: 'سبتمبر', fr: 'Septembre', en: 'September' },
  october: { ar: 'أكتوبر', fr: 'Octobre', en: 'October' },
  november: { ar: 'نوفمبر', fr: 'Novembre', en: 'November' },
  december: { ar: 'ديسمبر', fr: 'Décembre', en: 'December' },
  january: { ar: 'جانفي', fr: 'Janvier', en: 'January' },
  february: { ar: 'فيفري', fr: 'Février', en: 'February' },
  march: { ar: 'مارس', fr: 'Mars', en: 'March' },
  april: { ar: 'أفريل', fr: 'Avril', en: 'April' },
  may: { ar: 'ماي', fr: 'Mai', en: 'May' },
  june: { ar: 'جوان', fr: 'Juin', en: 'June' },
  enter_rejection_reason: { ar: 'أدخل سبب الرفض', fr: 'Entrez le motif du refus', en: 'Enter rejection reason' },
  please_enter_reason: { ar: 'يرجى إدخال سبب الرفض', fr: 'Veuillez entrer un motif de refus', en: 'Please enter a rejection reason' },
  logo_updated_success: { ar: 'تم تحديث الشعار بنجاح', fr: 'Logo mis à jour avec succès', en: 'Logo updated successfully' },
  request_submitted_success: { ar: 'تم تقديم الطلب بنجاح', fr: 'Demande soumise avec succès', en: 'Request submitted successfully' },
  certificate_prepared_success: { ar: 'تم إعداد الشهادة بنجاح', fr: 'Certificat préparé avec succès', en: 'Certificate prepared successfully' },
  notification_sent_to: { ar: 'تم إرسال إشعار إلى', fr: 'Notification envoyée à', en: 'Notification sent to' },
  suggest_defense: { ar: 'اقتراح موعد المناقشة', fr: 'Suggérer une date de soutenance', en: 'Suggest Defense Date' },
  defense_date: { ar: 'تاريخ المناقشة', fr: 'Date de soutenance', en: 'Defense Date' },
  defense_time: { ar: 'توقيت المناقشة', fr: 'Heure de soutenance', en: 'Defense Time' },
  defense_room: { ar: 'قاعة المناقشة', fr: 'Salle de soutenance', en: 'Defense Room' },
  confirm_defense: { ar: 'تأكيد موعد المناقشة', fr: 'Confirmer la soutenance', en: 'Confirm Defense' },
  defense_conflict: { ar: 'تعارض في موعد المناقشة', fr: 'Conflit de soutenance', en: 'Defense Conflict' },
  backup_restore: { ar: 'النسخ الاحتياطي والاستعادة', fr: 'Sauvegarde et Restauration', en: 'Backup & Restore' },
  download_backup: { ar: 'تحميل نسخة احتياطية', fr: 'Télécharger une sauvegarde', en: 'Download Backup' },
  restore_backup: { ar: 'استعادة نسخة احتياطية', fr: 'Restaurer une sauvegarde', en: 'Restore Backup' },
  academic_year_info: { ar: 'تغيير السنة الدراسية يقوم بتصفية جميع البيانات (المشاريع، الطلاب، الحصص) لإظهار السجلات الخاصة بتلك السنة فقط.', fr: 'Changer l\'année académique filtre toutes les données (projets, étudiants, séances) pour n\'afficher que les enregistrements de cette année.', en: 'Changing the academic year filters all data (projects, students, sessions) to show only records for that year.' },
  confirm_restore: { ar: 'هل أنت متأكد؟ سيؤدي هذا إلى الكتابة فوق البيانات الموجودة.', fr: 'Êtes-vous sûr ? Cela écrasera les données existantes.', en: 'Are you sure? This will overwrite existing data.' },
  restoring: { ar: 'جاري الاستعادة...', fr: 'Restauration...', en: 'Restoring...' },
  error: { ar: 'حدث خطأ', fr: 'Erreur', en: 'Error' },
  deleting_arabic_data: { ar: 'جاري حذف البيانات العربية...', fr: 'Suppression des données arabes...', en: 'Deleting Arabic data...' },
  arabic_data_deleted_success: { ar: 'تم حذف البيانات العربية بنجاح', fr: 'Données arabes supprimées avec succès', en: 'Arabic data deleted successfully' },
  delete_arabic_data: { ar: 'حذف البيانات العربية', fr: 'Supprimer les données arabes', en: 'Delete Arabic Data' },
  confirm_delete_arabic_data_title: { ar: 'تأكيد حذف البيانات العربية؟', fr: 'Confirmer la suppression des données arabes ?', en: 'Confirm Delete Arabic Data?' },
  confirm_delete_arabic_data_desc: { ar: 'سيؤدي هذا إلى حذف جميع التخصصات والمستويات التي تحتوي على أحرف عربية بشكل نهائي. لا يمكن التراجع عن هذا الإجراء.', fr: 'Cela supprimera définitivement toutes les spécialités et tous les niveaux contenant des caractères arabes. Cette action ne peut pas être annulée.', en: 'This will permanently delete all specialties and levels containing Arabic characters. This action cannot be undone.' },
  clear_all_schedules: { ar: 'مسح جميع الجداول', fr: 'Effacer tous les emplois du temps', en: 'Clear All Schedules' },
  clear_all_projects: { ar: 'مسح جميع المشاريع', fr: 'Effacer tous les projets', en: 'Clear All Projects' },
  confirm_clear_all_schedules_title: { ar: 'تأكيد مسح جميع الجداول؟', fr: 'Confirmer l\'effacement de tous les emplois du temps ?', en: 'Confirm Clear All Schedules?' },
  confirm_clear_all_schedules_desc: { ar: 'سيؤدي هذا إلى حذف جميع الجداول المحفوظة نهائياً. لا يمكن التراجع عن هذا الإجراء.', fr: 'Cela supprimera définitivement tous les emplois du temps enregistrés. Cette action ne peut pas être annulée.', en: 'This will permanently delete all saved schedules. This action cannot be undone.' },
  confirm_clear_all_projects_title: { ar: 'تأكيد مسح جميع المشاريع؟', fr: 'Confirmer l\'effacement de tous les projets ?', en: 'Confirm Clear All Projects?' },
  confirm_clear_all_projects_desc: { ar: 'سيؤدي هذا إلى حذف جميع المشاريع للسنة الدراسية الحالية نهائياً. لا يمكن التراجع عن هذا الإجراء.', fr: 'Cela supprimera définitivement tous les projets de l\'année académique en cours. Cette action ne peut pas être annulée.', en: 'This will permanently delete all projects for the current academic year. This action cannot be undone.' },
  clearing_data: { ar: 'جاري مسح البيانات...', fr: 'Effacement des données...', en: 'Clearing data...' },
  data_cleared_success: { ar: 'تم مسح البيانات بنجاح', fr: 'Données effacées avec succès', en: 'Data cleared successfully' },
  clone_to_next_year: { ar: 'نسخ للسنة القادمة', fr: 'Copier vers l\'année suivante', en: 'Clone to Next Year' },
  confirm_clone_schedule: { ar: 'تأكيد نسخ الجداول؟', fr: 'Confirmer la copie des emplois du temps ?', en: 'Confirm Clone Schedules?' },
  confirm_clone_schedule_desc: { ar: 'سيتم نسخ جميع جداول السنة الحالية إلى السنة الدراسية', fr: 'Tous les emplois du temps de l\'année en cours seront copiés vers l\'année académique', en: 'All schedules of the current year will be copied to the academic year' },
  cloning_schedule: { ar: 'جاري نسخ الجداول...', fr: 'Copie des emplois du temps...', en: 'Cloning schedules...' },
  clone_success: { ar: 'تم نسخ الجداول بنجاح', fr: 'Emplois du temps copiés avec succès', en: 'Schedules cloned successfully!' },
  active_academic_year: { ar: 'السنة الدراسية النشطة', fr: 'Année académique active', en: 'Active Academic Year' },
  academic_year_archiving: { ar: 'أرشفة السنوات الدراسية', fr: 'Archivage des années académiques', en: 'Academic Year Archiving' },
  confirm_delete_certificate: { ar: 'هل أنت متأكد من حذف هذه الشهادة؟', fr: 'Êtes-vous sûr de vouloir supprimer ce certificat ?', en: 'Are you sure you want to delete this certificate?' },
  delete_certificate: { ar: 'حذف الشهادة', fr: 'Supprimer le certificat', en: 'Delete Certificate' },
  manage_years: { ar: 'إدارة السنوات الدراسية', fr: 'Gérer les années', en: 'Manage Years' },
  birth_date: { ar: 'تاريخ الازدياد', fr: 'Date de naissance', en: 'Date of Birth' },
  birth_place: { ar: 'مكان الازدياد', fr: 'Lieu de naissance', en: 'Place of Birth' },
  select_years: { ar: 'اختر السنوات الدراسية', fr: 'Sélectionner les années académiques', en: 'Select Academic Years' },
  add_module_manually: { ar: 'إضافة مقياس يدوياً', fr: 'Ajouter un module manuellement', en: 'Add Module Manually' },
  add_project_manually: { ar: 'إضافة مشروع يدوياً', fr: 'Ajouter un projet manuellement', en: 'Add Project Manually' },
  modules_comma_separated: { ar: 'المقاييس (مفصولة بفاصلة)', fr: 'Modules (séparés par virgule)', en: 'Modules (comma separated)' },
  certificate_issued_success: { ar: 'تم إصدار الشهادة بنجاح', fr: 'Certificat délivré avec succès', en: 'Certificate issued successfully' },
  birth_details: { ar: 'معلومات الازدياد', fr: 'Détails de naissance', en: 'Birth Details' },
  academic_years: { ar: 'السنوات الدراسية', fr: 'Années académiques', en: 'Academic Years' },
  selected_modules: { ar: 'المقاييس المختارة', fr: 'Modules sélectionnés', en: 'Selected Modules' },
  selected_projects: { ar: 'المشاريع المختارة', fr: 'Projets sélectionnés', en: 'Selected Projects' },
  no_modules_found: { ar: 'لم يتم العثور على مقاييس', fr: 'Aucun module trouvé', en: 'No modules found' },
  no_projects_found: { ar: 'لم يتم العثور على مشاريع', fr: 'Aucun projet trouvé', en: 'No projects found' },
  confirm_request: { ar: 'تأكيد الطلب', fr: 'Confirmer la demande', en: 'Confirm Request' },
  birth_date_placeholder: { ar: 'تاريخ الازدياد', fr: 'Date de naissance', en: 'Birth Date' },
  birth_place_placeholder: { ar: 'مكان الازدياد', fr: 'Lieu de naissance', en: 'Birth Place' },
  student_names: { ar: 'أسماء الطلبة', fr: 'Noms des étudiants', en: 'Student Names' },
  new_request_notification: { ar: 'هناك طلب شهادة جديد', fr: 'Nouvelle demande de certificat', en: 'New certificate request' },
  restore_success: { ar: 'تمت استعادة البيانات بنجاح', fr: 'Données restaurées avec succès', en: 'Data restored successfully' },
  restore_error: { ar: 'فشلت استعادة البيانات', fr: 'Échec de la restauration des données', en: 'Failed to restore data' },
  confirm_restore_title: { ar: 'تأكيد الاستعادة', fr: 'Confirmer la restauration', en: 'Confirm Restore' },
  select_level: { ar: 'اختر المستوى', fr: 'Sélectionner le niveau', en: 'Select Level' },
  download_word: { ar: 'تحميل Word', fr: 'Télécharger Word', en: 'Download Word' },
  year_added_success: { ar: 'تم إضافة السنة بنجاح', fr: 'Année ajoutée avec succès', en: 'Year added successfully' },
  year_deleted_success: { ar: 'تم حذف السنة بنجاح', fr: 'Année supprimée avec succès', en: 'Year deleted successfully' },
  cannot_delete_last_year: { ar: 'لا يمكن حذف آخر سنة دراسية', fr: 'Impossible de supprimer la dernière année', en: 'Cannot delete the last academic year' },
  year_exists: { ar: 'هذه السنة موجودة بالفعل', fr: 'Cette année existe déjà', en: 'This year already exists' },
  field_visits: { ar: 'الزيارات الميدانية', fr: 'Visites de terrain', en: 'Field Visits' },
  request_field_visit: { ar: 'طلب زيارة ميدانية', fr: 'Demander une visite de terrain', en: 'Request Field Visit' },
  company_name: { ar: 'اسم الشركة', fr: 'Nom de l\'entreprise', en: 'Company Name' },
  visit_date: { ar: 'تاريخ الزيارة', fr: 'Date de la visite', en: 'Visit Date' },
  student_count_visit: { ar: 'عدد الطلبة', fr: 'Nombre d\'étudiants', en: 'Student Count' },
  supervising_teachers: { ar: 'الأساتذة المؤطرون', fr: 'Enseignants encadrants', en: 'Supervising Teachers' },
  add_supervisor: { ar: 'إضافة مؤطر', fr: 'Ajouter un encadrant', en: 'Add Supervisor' },
  proposed_visit_details: { ar: 'تفاصيل الزيارة المقترحة', fr: 'Détails de la visite proposée', en: 'Proposed Visit Details' },
  send_to_committee: { ar: 'إرسال إلى اللجنة', fr: 'Envoyer au comité', en: 'Send to Committee' },
  upload_thesis: { ar: 'رفع المذكرة النهائية', fr: 'Télécharger le mémoire final', en: 'Upload Final Thesis' },
  thesis_sent_success: { ar: 'تم إرسال المذكرة بنجاح', fr: 'Mémoire envoyé avec succès', en: 'Thesis sent successfully' },
  ai_assistant: { ar: 'مساعد الذكاء الاصطناعي', fr: 'Assistant IA', en: 'AI Assistant' },
  ai_placeholder: { ar: 'اسأل عن الجداول، الإحصائيات، أو أي شيء يخص القسم...', fr: 'Posez des questions sur les horaires, les statistiques...', en: 'Ask about schedules, stats, or anything about the department...' },
  university_name: { ar: 'جامعة عمار ثليجي - الأغواط', fr: 'Université Amar Telidji - Laghouat', en: 'Amar Telidji University - Laghouat' },
  faculty_name: { ar: 'كلية التكنولوجيا', fr: 'Faculté de Technologie', en: 'Faculty of Technology' },
  department_name: { ar: 'قسم الهندسة الميكانيكية', fr: 'Département de Génie Mécanique', en: 'Department of Mechanical Engineering' },
  username: { ar: 'اسم المستخدم (البريد)', fr: 'Nom d\'utilisateur (Email)', en: 'Username (Email)' },
  login_button: { ar: 'تسجيل الدخول', fr: 'Se connecter', en: 'Login' },
  login_to_system: { ar: 'الدخول إلى النظام', fr: 'Accéder au système', en: 'Login to System' },
  email_welcome: { ar: 'مرحباً {name}،', fr: 'Bonjour {name},', en: 'Hello {name},' },
  email_account_created: { ar: 'تم إنشاء حسابك بنجاح في نظام إدارة القسم - جامعة الأغواط.', fr: 'Votre compte a été créé avec succès dans le système de gestion du département - Université de Laghouat.', en: 'Your account has been successfully created in the Department Management System - Laghouat University.' },
  email_login_details: { ar: 'بيانات الدخول الخاصة بك:', fr: 'Vos identifiants de connexion :', en: 'Your login credentials:' },
  email_link_fallback: { ar: 'إذا لم يعمل الزر، يمكنك نسخ الرابط التالي ولصقه في متصفحك:', fr: 'Si le bouton ne fonctionne pas, vous pouvez copier et coller le lien suivant dans votre navigateur :', en: 'If the button doesn\'t work, you can copy and paste the following link into your browser:' },
  email_thanks: { ar: 'شكراً لك،', fr: 'Merci,', en: 'Thank you,' },
  email_signature: { ar: 'قسم الهندسة الميكانيكية', fr: 'Département de Génie Mécanique', en: 'Department of Mechanical Engineering' },
  email_subject_account: { ar: 'تفاصيل حسابك في نظام إدارة القسم - جامعة الأغواط', fr: 'Détails de votre compte dans le système de gestion du département - Université de Laghouat', en: 'Your account details in the Department Management System - Laghouat University' },
  or_continue_with: { ar: 'أو المتابعة باستخدام', fr: 'Ou continuer avec', en: 'Or continue with' },
  google_login: { ar: 'جوجل', fr: 'Google', en: 'Google' },
  change_password: { ar: 'تغيير كلمة المرور', fr: 'Changer le mot de passe', en: 'Change Password' },
  new_password: { ar: 'كلمة المرور الجديدة', fr: 'Nouveau mot de passe', en: 'New Password' },
  confirm_password: { ar: 'تأكيد كلمة المرور', fr: 'Confirmer le mot de passe', en: 'Confirm Password' },
  passwords_dont_match: { ar: 'كلمات المرور غير متطابقة', fr: 'Les mots de passe ne correspondent pas', en: 'Passwords don\'t match' },
  password_update_success: { ar: 'تم تحديث كلمة المرور بنجاح', fr: 'Mot de passe mis à jour avec succès', en: 'Password updated successfully' },
  update_password: { ar: 'تحديث كلمة المرور', fr: 'Mettre à jour le mot de passe', en: 'Update Password' },
  password_too_short: { ar: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل', fr: 'Le mot de passe doit comporter au moins 6 caractères', en: 'Password must be at least 6 characters' },
  // Overtime Calculation
  teachers_analyzed: { ar: 'أستاذ تم تحليل بياناتهم', fr: 'enseignants analysés', en: 'teachers analyzed' },
  calculation_settings: { ar: 'إعدادات الحساب', fr: 'Paramètres de calcul', en: 'Calculation Settings' },
  invigilation_rate: { ar: 'معدل الحراسة', fr: 'Taux de surveillance', en: 'Invigilation Rate' },
  h_per_session: { ar: 'ساعة/حصة', fr: 'h/séance', en: 'h/session' },
  supervision_rate: { ar: 'معدل التأطير', fr: 'Taux d\'encadrement', en: 'Supervision Rate' },
  h_per_project: { ar: 'ساعة/مشروع', fr: 'h/projet', en: 'h/project' },
  search_teachers_placeholder: { ar: 'البحث عن الأساتذة بالاسم...', fr: 'Rechercher des enseignants par nom...', en: 'Search teachers by name...' },
  all_types: { ar: 'جميع الأنواع', fr: 'Tous les types', en: 'All Types' },
  no_rank: { ar: 'بدون رتبة', fr: 'Sans grade', en: 'No Rank' },
  permanent: { ar: 'دائم', fr: 'Permanent', en: 'Permanent' },
  submitted_successfully: { ar: 'تم التقديم بنجاح', fr: 'Soumis avec succès', en: 'Submitted successfully' },
  approved_successfully: { ar: 'تم التأكيد بنجاح', fr: 'Approuvé avec succès', en: 'Approved successfully' },
  rejected_successfully: { ar: 'تم الرفض بنجاح', fr: 'Refusé avec succès', en: 'Rejected successfully' },
  calculation_info: { ar: 'كيفية الحساب', fr: 'Comment c\'est calculé', en: 'How it\'s calculated' },
  calculation_info_desc: { ar: 'يتم حساب الساعات الإضافية بناءً على النصاب القانوني (9 ساعات للأساتذة الدائمين) ومجموع ساعات التدريس فقط (الدروس والتطبيقات).', fr: 'Les heures supplémentaires sont calculées sur la base de la charge statutaire (9h pour les permanents) et du total des heures d\'enseignement uniquement.', en: 'Overtime hours are calculated based on the standard workload (9h for permanent staff) and the total of teaching hours only.' },
  overtime_new_calc_note: { ar: 'يتم حساب الساعات الإضافية بناءً على ساعات التدريس فقط (Modules)، بعد طرح النصاب القانوني (9 ساعات) للأساتذة الدائمين.', fr: 'Les heures supplémentaires sont calculées sur la base des heures d\'enseignement uniquement (Modules), après déduction de la charge statutaire (9h) pour les permanents.', en: 'Overtime is calculated based on TEACHING hours only (Modules), minus the 9h legal quota for permanent teachers.' },
  invigilation_not_in_sum: { ar: 'للمعلومات فقط، لا تدخل في مجموع الساعات الإضافية.', fr: 'Pour information uniquement, non inclus dans le calcul des HMS.', en: 'For information only, not included in overtime sum.' },
  supervision_not_in_sum: { ar: 'للمعلومات فقط، لا تدخل في مجموع الساعات الإضافية.', fr: 'Pour information uniquement, non inclus dans le calcul des HMS.', en: 'For information only, not included in overtime sum.' },
  teaching_calc: { ar: 'التدريس: محاضرة = 2.25 ساعة، TD/TP = 1.5 ساعة.', fr: 'Enseignement : Cours = 2.25h, TD/TP = 1.5h.', en: 'Teaching: Lecture = 2.25h, TD/TP = 1.5h.' },
  invigilation_calc: { ar: 'الحراسة: {rate} ساعة لكل حصة حراسة مسجلة.', fr: 'Surveillance : {rate}h par séance de surveillance enregistrée.', en: 'Invigilation: {rate}h per recorded invigilation session.' },
  supervision_calc: { ar: 'التأطير: {rate} ساعة لكل مشروع تخرج عادي.', fr: 'Encadrement : {rate}h par projet de fin d\'études standard.', en: 'Supervision: {rate}h per standard graduation project.' },
  supervision_1275_calc: { ar: 'تأطير القرار 1275: 12 ساعة لكل مشروع (Startup/Patent).', fr: 'Encadrement Décision 1275 : 12h par projet (Startup/Patent).', en: 'Decision 1275 Supervision: 12h per project (Startup/Patent).' },
  threshold_1275_calc: { ar: 'تخفيض النصاب: يتم تخفيض النصاب القانوني بـ 3 ساعات للأساتذة ضمن القرار 1275.', fr: 'Réduction de charge : La charge statutaire est réduite de 3h pour les enseignants sous le décret 1275.', en: 'Workload Reduction: The standard workload is reduced by 3h for Decision 1275 teachers.' },
  export: { ar: 'تصدير', fr: 'Exporter', en: 'Export' },
  decision_1275_note: { ar: 'ملاحظة: الأساتذة ضمن القرار 1275 قد تخضع ساعاتهم لقواعد خاصة عند استخراج الكشوف النهائية.', fr: 'Note : Les enseignants sous le décret 1275 peuvent avoir des règles spécifiques lors de l\'extraction des rapports finaux.', en: 'Note: Decision 1275 teachers may have specific rules applied during final reporting.' },
  total_overtime: { ar: 'إجمالي الساعات الإضافية', fr: 'Total des heures supplémentaires', en: 'Total Overtime' },
  teaching: { ar: 'التدريس', fr: 'Enseignement', en: 'Teaching' },
  invigilation: { ar: 'الحراسة', fr: 'Surveillance', en: 'Invigilation' },
  supervision: { ar: 'التأطير', fr: 'Encadrement', en: 'Supervision' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  academicYear: string;
  setAcademicYear: (year: string) => void;
  academicYears: string[];
  updateAcademicYears: (years: string[]) => Promise<void>;
  t: (key: string, params?: Record<string, string>) => string;
  isRTL: boolean;
  getPublicUrl: () => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_lang');
    return (saved as Language) || 'ar';
  });

  const [academicYear, setAcademicYear] = useState<string>(() => {
    const saved = localStorage.getItem('app_academic_year');
    return saved || '2025/2026';
  });

  const [academicYears, setAcademicYears] = useState<string[]>(['2024/2025', '2025/2026', '2026/2027']);

  const fetchYears = async () => {
    try {
      const settings = await dbService.getDocument<{ years: string[] }>('settings', 'global');
      if (settings?.years && settings.years.length > 0) {
        setAcademicYears(settings.years);
        // If current year is not in the list, pick the first one
        if (!settings.years.includes(academicYear)) {
          setAcademicYear(settings.years[0]);
        }
      }
    } catch (error) {
      console.error('Failed to fetch academic years:', error);
    }
  };

  useEffect(() => {
    fetchYears();
  }, []);

  const updateAcademicYears = async (years: string[]) => {
    await dbService.setDocument('settings', 'global', { years });
    setAcademicYears(years);
  };

  useEffect(() => {
    localStorage.setItem('app_lang', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    localStorage.setItem('app_academic_year', academicYear);
  }, [academicYear]);

  const t = (key: string, params?: Record<string, string>) => {
    let text = translations[key]?.[language] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  };

  const getPublicUrl = () => {
    const defaultUrl = (process.env as any).APP_URL || window.location.origin;
    const currentUrl = window.location.origin;
    
    const isLocal = currentUrl.includes('localhost') || 
                    currentUrl.includes('127.0.0.1') || 
                    currentUrl.includes('192.168.') || 
                    currentUrl.includes('0.0.0.0') ||
                    currentUrl.includes('-dev-');
    
    // If local, return the configured public URL
    if (isLocal) {
      return defaultUrl;
    }
    
    // If it's already a public URL, return as is
    return currentUrl;
  };

  const value = {
    language,
    setLanguage,
    academicYear,
    setAcademicYear,
    academicYears,
    updateAcademicYears,
    t,
    isRTL: language === 'ar',
    getPublicUrl,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
